name: unhexennium
description: A chemistry-oriented calculator.

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  # md
  uses-material-design: true
  # fonts
  fonts:
    - family: Stix2Math
      fonts:
        - asset: fonts/STIX2Math.otf
  assets:
    - imgs/arrows/spinempty.gif
    - imgs/arrows/spinsingle.gif
    - imgs/arrows/spinpair.gif