name: unhexennium
description: A chemistry-oriented calculator.

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  # md
  uses-material-design: true
  # fonts
  fonts:
    - family: CMU
      fonts:
        - asset: fonts/computer-modern-serif-italics.ttf
          style: italic